apiVersion: v1
kind: Service
metadata:
  name: myecommerce-app
  namespace: demo
spec:
  selector:
    app: myecommerce-app
    color: blue   # <-- switch to green to route traffic to green deployment
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
