apiVersion: apps/v1
kind: Deployment
metadata:
  name: myecommerce-app
  labels:
    app: myecommerce
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myecommerce
  template:
    metadata:
      labels:
        app: myecommerce
    spec:
      containers:
      - name: frontend
        
        image: rukevweubio/my-ecommerceapp:latest 
        ports:
        - containerPort: 80
     