apiVersion: v1
kind: Service
metadata:
  name: myecommerce-service
spec:
  selector:
    app: myecommerce
  ports:
    - protocol: TCP
      port: 80        
      targetPort: 80   
  type: LoadBalancer