name: Build, Scan, and Deploy to GKE

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  GKE_PROJECT_ID: ${{ secrets.GKE_PROJECT_ID }}
  GKE_CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}

jobs:
  build-and-deploy:
    name: Build, Scan, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t my-ecommerceapp:latest .

      - name: Save Docker image to tar
        run: |
          docker save my-ecommerceapp:latest -o my-ecommerceapp.tar
      - name: Load Docker image for Trivy
        run: |
          docker load -i my-ecommerceapp.tar

      - name: Scan Docker image locally with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: my-ecommerceapp:latest
          scan-type: image
          format: table
          exit-code: '1'   # fail workflow if vulnerabilities found

      - name: Push Docker image to Docker Hub
        run: |
          docker tag my-ecommerceapp:latest ${{ env.DOCKER_USERNAME }}/my-ecommerceapp:latest
          docker push ${{ env.DOCKER_USERNAME }}/my-ecommerceapp:latest

      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v0.4.0
        with:
          cluster_name: ${{ env.GKE_CLUSTER_NAME }}
          location: ${{ env.GKE_ZONE }}
          project_id: ${{ env.GKE_PROJECT_ID }}

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Deploy to GKE using kubectl
        run: |
          kubectl apply -f manifest/deployment.yaml --namespace=dev
          kubectl apply -f manifest/service.yaml --namespace=dev
          kubectl rollout status deployment/myecommerce-app --namespace=dev