name: create a gitaction workflow that build the docker image. and deploy the image to  the gke cluster 

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  GKE_PROJECT_ID: ${{ secrets.GKE_PROJECT_ID }}
  GKE_CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }} 




jobs: 
  build:
    name: Build and Deploy to GKE
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
          
      - name: used trivy scan on teh dcoker image 
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.DOCKER_USERNAME }}/my-app:latest
          scan-type: "image"
          format: "table"

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ${{ env.DOCKER_USERNAME }}/my-app:latest


      - name: used trivy scan on teh dcoker image 
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.DOCKER_USERNAME }}/my-app:latest
          scan-type: "image"
          format: "table"
          exit-code: '1'


      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v0.4.0
        with:
          cluster_name: ${{ env.GKE_CLUSTER_NAME }}
          location: ${{ env.GKE_ZONE }}
          project_id: ${{ env.GKE_PROJECT_ID }}


      - name: used  helm to deploy the application to gke cluster
        uses: deliverybot/helm@v1
        with:
          args: upgrade --install my-release ./helm-chart --set image.repository=${{ env.DOCKER_USERNAME }}/my-app,image.tag=latest

      - name: Deploy to GKE
        run: |
          kubectl set image deployment/my-deployment my-container=${{ env.DOCKER_USERNAME }}/my-app:latest
          kubectl rollout status deployment/my-deployment